- hosts: all
  tasks:
    - name: Debug
      debug:
        msg: "123"
    - name: just test
      debug:
        msg: 'haha'
    - name: shell test
      shell: sdfdg
      register: test_status
      retries: 3
      delay: 5
      until: '"stder2r" in test_status'
      ignore_errors: yes
    - name: test1
      debug:
        msg: test_status
